# Name of the workflow that will appear in the "Actions" tab of the repository.
name: 'Dependency review'

# Specifies the events that trigger this workflow.
# In this case, the workflow runs when a Pull Request is opened, updated, or synchronized
# against the specified branches (main, develop, or any branch matching the pattern feature/*).
on:
  pull_request:
    branches:
      - main
      - develop
      - "feature/*"

# Permissions required for the workflow to function correctly.
# - contents: read -> Allows reading the contents of the repository.
# - pull-requests: write -> Required to use the "comment-summary-in-pr" option, which
#   adds a comment in the Pull Request with a summary of the analysis.
permissions:
  contents: read
  pull-requests: write

# Definition of the jobs for this workflow.
# A job is a unit of work executed on a specified runner.
jobs:
  dependency-review:
    # Specifies the execution environment. This job will run on GitHub-hosted
    # runners using the latest Ubuntu image.
    runs-on: ubuntu-latest

    # A collection of steps to be executed as part of the job.
    steps:
      # Step 1: Checkout the code from the repository.
      # This is necessary for the workflows to access the repository files and history.
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      # Step 2: Run the Dependency Review action.
      # This action scans for any modified or introduced dependencies in the PR
      # and checks for known vulnerabilities in those dependencies.
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          # Enable commenting a summary of the dependency analysis directly in the Pull Request.
          comment-summary-in-pr: always